export const knowledgeBase = [
  {
    id: "prerequisites-general",
    title: "Python Base Requirements & Virtual Environments",
    category: "getting-started",
    content: "VScanX requires Python 3.11+ and is compatible with macOS, Linux, and Windows. We strongly recommend executing installation inside a clean virtual environment (python -m venv venv followed by 'source venv/bin/activate' on macOS/Linux or 'venv\\Scripts\\activate' on Windows). administrative raw socket permissions are required solely for active Scapy sniffing probers.",
    tags: ["python", "installation", "venv", "virtualenv", "activate", "getting-started"],
    relatedSchemas: ["Environment Configuration schema"],
    relatedCommands: [
      "python -m venv venv",
      "source venv/bin/activate",
      "venv\\Scripts\\activate"
    ],
    workflowStages: ["Stage 1: Python Virtual Environment Activation"],
    replayContexts: ["Local Python Execution Environment"],
    relatedDocs: ["prerequisites-scapy", "prerequisites-docker"]
  },
  {
    id: "prerequisites-scapy",
    title: "Scapy Raw Sockets & Sudo Privileges",
    category: "getting-started",
    content: "VScanX uses Scapy for packet sniffing and active scanning. Because Scapy operates at the network interface layer, Windows requires raw socket interfaces via Npcap or WinPcap (must be run with administrative command prompt). Linux and macOS require 'sudo vscanx scan' to bind raw socket adapters.",
    tags: ["scapy", "npcap", "winpcap", "sudo", "sockets", "permissions"],
    relatedSchemas: ["Packet Header Structure"],
    relatedCommands: ["sudo vscanx scan 127.0.0.1 --verify"],
    workflowStages: ["Stage 1: Raw Sockets Initialization"],
    replayContexts: ["Active packet crafting boundaries"],
    relatedDocs: ["prerequisites-general", "cli-scan"]
  },
  {
    id: "prerequisites-docker",
    title: "Docker Containment Prerequisites",
    category: "getting-started",
    content: "Active vulnerability verification loops spawn ephemeral containers. The local host environment must run a functioning Docker daemon accessible by the current shell user. In CI/CD pipelines lacking Docker socket mappings, select the '--verify-mode local-only' flag to trigger passive signature audits.",
    tags: ["docker", "daemon", "containers", "ci-cd", "verification-mode"],
    relatedSchemas: ["Docker Container Configuration Specs"],
    relatedCommands: ["vscanx scan target.local --verify --verify-mode local-only"],
    workflowStages: ["Stage 3: Sandbox Container Spawning"],
    replayContexts: ["Docker container containment"],
    relatedDocs: ["prerequisites-general", "verification-workflow-sandbox-spawner"]
  },
  {
    id: "cli-scan",
    title: "vscanx scan Command Specifications",
    category: "getting-started",
    content: "The primary command 'vscanx scan <target> --verify' initiates scanning. It loops through active modules (web, web3, ai), captures anomalies on the event bus, and validates them via isolated containers. Passive scans bypass active exploits verification using the '--passive' flag.",
    tags: ["cli", "scan", "verify", "passive", "recipes"],
    relatedSchemas: ["CLI Arguments Schema"],
    relatedCommands: ["vscanx scan target.local --verify", "vscanx scan target.local --passive"],
    workflowStages: ["Stage 1: Passive Probing", "Stage 4: Active Exploit Verification"],
    replayContexts: ["Verification over Speculation Mode"],
    relatedDocs: ["prerequisites-general", "cli-replay"]
  },
  {
    id: "cli-replay",
    title: "vscanx replay Snapshot Injection",
    category: "getting-started",
    content: "Replays a serialized security snap run state: 'vscanx replay --replay-id <id>'. It reads snap JSON logs from the local '.vscanx_state/' directory, re-injects validators, and runs exploit validations against identical replicas without target network re-probing.",
    tags: ["cli", "replay", "replay-id", "snapshots", "recipes"],
    relatedSchemas: ["Snapshot State JSON Schema"],
    relatedCommands: ["vscanx replay --replay-id scan_701D"],
    workflowStages: ["Stage 3: Container Replication", "Stage 4: Exploit Re-Verification"],
    replayContexts: ["Immutable Replay Snap Execution"],
    relatedDocs: ["cli-scan", "cli-diff", "schema-scan-snapshot"]
  },
  {
    id: "cli-diff",
    title: "vscanx diff Delta Regression Comparison",
    category: "getting-started",
    content: "Compares snapshot baseline states: 'vscanx diff --diff <runA> <runB>'. By evaluating delta signatures between snapshots, the diff engine determines if vulnerabilities identified in run A have been successfully mitigated (RESOLVED) or remain open (ACTIVE) under run B.",
    tags: ["cli", "diff", "delta", "regression", "recipes"],
    relatedSchemas: ["State Comparison Diff Schema"],
    relatedCommands: ["vscanx diff --diff scan_701C scan_701D"],
    workflowStages: ["Stage 5: Canonical Findings Regression Analysis"],
    replayContexts: ["Security State Transitions S(t) -> S(t+1)"],
    relatedDocs: ["cli-replay", "core-concepts-security-states"]
  },
  {
    id: "core-principles-verification",
    title: "Principle: Verification over Speculation",
    category: "core-concepts",
    content: "To achieve 0% false positives, VScanX enforces a critical verification guideline: passive banner scans or signatures act strictly as detection anomalies. They are never reported. Instead, an exploit validator must actively reproduce the vulnerability inside a secure container sandbox to confirm it.",
    tags: ["principles", "verification", "speculation", "false-positives", "philosophy"],
    relatedSchemas: ["Canonical Findings JSON Schema"],
    relatedCommands: ["vscanx scan <target> --verify"],
    workflowStages: ["Stage 1: Passive Probing", "Stage 4: Active Exploit Verification"],
    replayContexts: ["Verification over Speculation Engine"],
    relatedDocs: ["core-principles-reproducibility", "verification-workflow-exploit-validation"]
  },
  {
    id: "core-principles-reproducibility",
    title: "Principle: Replay over Ephemeral Scans",
    category: "core-concepts",
    content: "Traditional network scanners treat audits as ephemeral logs. VScanX models runs as reproducible state snap records. State Snapshots capturing environment baselines, event queues, and traces are serialized, permitting engineers to re-verify state regression deterministically on local hosts.",
    tags: ["principles", "reproducibility", "replay", "snapshots", "philosophy"],
    relatedSchemas: ["Snapshot State JSON Schema"],
    relatedCommands: ["vscanx replay --replay-id <id>"],
    workflowStages: ["Stage 5: Canonical Findings Reporting"],
    replayContexts: ["Security Regression State Replication"],
    relatedDocs: ["schema-scan-snapshot", "core-principles-verification"]
  },
  {
    id: "core-concepts-security-states",
    title: "Systems as Evolving Security States",
    category: "core-concepts",
    content: "VScanX treats target environments as state machines S(t) -> S(t+1). Instead of textual summaries, baseline targets model as immutable JSON hashes. During regression checks, VScanX verifies if exploit triggers succeed on local replica sandboxes, mathematically proving patch verification.",
    tags: ["security-states", "state-machine", "regression", "snapshot", "evolving-states"],
    relatedSchemas: ["Security State Hash Schema"],
    relatedCommands: ["vscanx diff --diff <runA> <runB>"],
    workflowStages: ["Stage 5: Canonical Findings Deltas"],
    replayContexts: ["Security State Transitions S(t) -> S(t+1)"],
    relatedDocs: ["core-principles-verification", "cli-diff"]
  },
  {
    id: "verification-workflow-passive",
    title: "Stage 1: Passive Probing",
    category: "workflow",
    content: "The initial stage of the verification lifecycle. Discovery engines passively analyze endpoints, routes, and smart contract structures using minimal network scans, searching for anomalies without triggering active exploit pathways.",
    tags: ["lifecycle", "stage-1", "passive", "probing", "discovery"],
    relatedSchemas: ["Discovery Probe Interface"],
    relatedCommands: ["vscanx scan <target> --passive"],
    workflowStages: ["Stage 1: Passive Probing"],
    replayContexts: ["Passive network observation state"],
    relatedDocs: ["verification-workflow-event-bus", "cli-scan"]
  },
  {
    id: "verification-workflow-event-bus",
    title: "Stage 2: Event Dispatching",
    category: "workflow",
    content: "Decouples detection from validation. When a prober discovers an anomaly, it publishes a typed event contract (e.g., SSRF_PROBE_ANOMALY, WEB3_REENTRANCY_ANOMALY) containing target payloads to the central event broker.",
    tags: ["lifecycle", "stage-2", "event-bus", "decoupling", "broker"],
    relatedSchemas: ["Typed Event Contracts Schema"],
    relatedCommands: ["vscanx scan <target> --verify"],
    workflowStages: ["Stage 2: Event Dispatching"],
    replayContexts: ["Decoupled Event Pipeline Queueing"],
    relatedDocs: ["verification-workflow-passive", "verification-workflow-sandbox-spawner"]
  },
  {
    id: "verification-workflow-sandbox-spawner",
    title: "Stage 3: Sandbox Container Spawning",
    category: "workflow",
    content: "Upon intercepting an event contract, the orchestrator provisions an isolated containment sandbox based on the vulnerability type: Docker container replicas for Web APIs, Anvil local node forks for Web3 contracts, or gVisor for AI prompts.",
    tags: ["lifecycle", "stage-3", "sandbox", "spawner", "isolation", "containment"],
    relatedSchemas: ["Sandbox Containment Policy Descriptors"],
    relatedCommands: ["vscanx scan <target> --verify"],
    workflowStages: ["Stage 3: Sandbox Container Spawning"],
    replayContexts: ["Local container isolation containment"],
    relatedDocs: ["verification-workflow-event-bus", "verification-workflow-exploit-validation", "verification-workflow-sandbox-anvil"]
  },
  {
    id: "verification-workflow-exploit-validation",
    title: "Stage 4: Active Exploit Verification",
    category: "workflow",
    content: "VScanX executes dynamic exploit scripts against the isolated sandbox container via loopback interfaces. Only if the exploit succeeds inside the containment sandbox is the vulnerability verified, ensuring 0% false positives.",
    tags: ["lifecycle", "stage-4", "active", "validation", "exploit"],
    relatedSchemas: ["Exploit Validator Interface"],
    relatedCommands: ["vscanx scan <target> --verify"],
    workflowStages: ["Stage 4: Active Exploit Verification"],
    replayContexts: ["Verification sandbox active exploit checks"],
    relatedDocs: ["verification-workflow-sandbox-spawner", "verification-workflow-canonical-findings"]
  },
  {
    id: "verification-workflow-canonical-findings",
    title: "Stage 5: Canonical Reporting",
    category: "workflow",
    content: "Proven vulnerabilities compile into a structured canonical findings JSON record. Unverified anomalies are discarded. Verified findings transition to ACTIVE states, and subsequent scans can mathematically resolve them.",
    tags: ["lifecycle", "stage-5", "canonical", "report", "findings"],
    relatedSchemas: ["Canonical Findings JSON Schema"],
    relatedCommands: ["vscanx scan <target> --verify"],
    workflowStages: ["Stage 5: Canonical Reporting"],
    replayContexts: ["Verified findings state tracking"],
    relatedDocs: ["verification-workflow-exploit-validation", "schema-canonical-finding"]
  },
  {
    id: "verification-workflow-sandbox-anvil",
    title: "Anvil EVM Sandbox Containment",
    category: "workflow",
    content: "For Web3 smart contracts, VScanX forks a local Ethereum RPC node using Anvil at the target trigger block height. Active validators execute recursive withdrawal balance mutations against this isolated node fork, avoiding target state contamination.",
    tags: ["sandbox", "anvil", "evm", "web3", "forking", "reentrancy"],
    relatedSchemas: ["EVM Fork RPC Payload Schema"],
    relatedCommands: ["vscanx scan <rpc-node> --scan-type web3 --verify"],
    workflowStages: ["Stage 3: Anvil EVM Sandbox Spawn", "Stage 4: Blockchain exploit validation"],
    replayContexts: ["Anvil local RPC node blockchain forking"],
    relatedDocs: ["verification-workflow-sandbox-spawner", "modules-web3-reentrancy"]
  },
  {
    id: "verification-workflow-sandbox-gvisor",
    title: "gVisor runsc Containment",
    category: "workflow",
    content: "Auditing agentic AI systems for command escapes requires strict isolation. VScanX spawns secure gVisor (runsc) container sandboxes. This intercepts kernel-level RCE escape attempts, protecting the host system node.",
    tags: ["sandbox", "gvisor", "runsc", "ai", "containment", "rce"],
    relatedSchemas: ["gVisor sandbox descriptors"],
    relatedCommands: ["vscanx scan <llm-endpoint> --scan-type agentic --verify"],
    workflowStages: ["Stage 3: gVisor container spawning", "Stage 4: RCE containment checks"],
    replayContexts: ["runsc gVisor Kernel Isolation Containment"],
    relatedDocs: ["verification-workflow-sandbox-spawner", "modules-ai-breakout"]
  },
  {
    id: "schema-canonical-finding",
    title: "Canonical Findings JSON Schema Structure",
    category: "findings",
    content: "Enforces a strict JSON finding data contract: 'finding_id' (VSC-YYYY-XXXX), 'target', 'module', 'verification_state' (VERIFIED, ACTIVE, RESOLVED), 'severity' (LOW, MEDIUM, HIGH, CRITICAL), and 'evidence_trace' capturing HTTP frames, EVM state shifts, or breakout logs.",
    tags: ["json-schema", "findings", "verification-state", "finding-id", "contract"],
    relatedSchemas: ["finding_id (VSC-YYYY-XXXX) Contract", "evidence_trace Schema Contract"],
    relatedCommands: ["vscanx scan <target> --verify"],
    workflowStages: ["Stage 5: Canonical Reporting"],
    replayContexts: ["VERIFIED, ACTIVE, or RESOLVED status contract"],
    relatedDocs: ["verification-workflow-canonical-findings", "cli-diff"]
  },
  {
    id: "schema-scan-snapshot",
    title: "Scan Snapshot JSON Structure",
    category: "replay-diff",
    content: "Serialized baselines: snap_<id>.json. Contains target meta, event bus sequence traces, container logs, and findings. Replay snapshots can be injected back into orchestrators to verify regression.",
    tags: ["json-schema", "snapshot", "replay-id", "state-file"],
    relatedSchemas: ["snap_<id>.json Schema Contract"],
    relatedCommands: ["vscanx replay --replay-id scan_701D"],
    workflowStages: ["Stage 5: Baseline Serialization"],
    replayContexts: ["Immutable baseline state serialization"],
    relatedDocs: ["cli-replay", "cli-diff"]
  },
  {
    id: "modules-web-sqli",
    title: "SQLi Scanning & Validation",
    category: "modules",
    content: "Web auditing maps SQL injection via 'sqli_detector.py'. On flagging passive anomalies, VScanX spawns isolated 'vscanx/val-web:latest' Docker containers and injects validator payloads to verify database breakout.",
    tags: ["web-modules", "sqli", "sqli-detector", "sql-injection"],
    relatedSchemas: ["SQLI_PROBE_ANOMALY Event Contract"],
    relatedCommands: ["vscanx scan <target> --verify"],
    workflowStages: ["Stage 1: Passive Probing", "Stage 3: Docker Sandbox Spawn", "Stage 4: SQLi validation"],
    replayContexts: ["SQLi container loopback validation"],
    relatedDocs: ["prerequisites-docker", "modules-web-ssrf"]
  },
  {
    id: "modules-web-ssrf",
    title: "SSRF Probe Verification",
    category: "modules",
    content: "SSRF checking maps Server-Side Request Forgery via 'ssrf_detector.py'. Anomalies trigger 'SSRF_PROBE_ANOMALY' events, prompting clean Docker containment clones to execute loopback request validator payloads.",
    tags: ["web-modules", "ssrf", "ssrf-detector", "ssrf-probe"],
    relatedSchemas: ["SSRF_PROBE_ANOMALY Event Contract"],
    relatedCommands: ["vscanx scan <target> --verify"],
    workflowStages: ["Stage 1: Passive Probing", "Stage 3: Docker Sandbox Spawn", "Stage 4: SSRF verification"],
    replayContexts: ["Docker container network isolation"],
    relatedDocs: ["prerequisites-docker", "modules-web-sqli"]
  },
  {
    id: "modules-web3-reentrancy",
    title: "Web3 Reentrancy Verification",
    category: "modules",
    content: "Audits recursive withdrawals via 'reentrancy_analyzer.py'. bytecode AST scanners flag anomalies, triggering 'WEB3_REENTRANCY_ANOMALY' events. Local Anvil EVM node forks run attacker contracts to prove reentrancy.",
    tags: ["web3-modules", "reentrancy", "reentrancy-analyzer", "solidity", "ast"],
    relatedSchemas: ["WEB3_REENTRANCY_ANOMALY Event Contract", "EVM AST Node Representation"],
    relatedCommands: ["vscanx scan <rpc-node> --scan-type web3 --verify"],
    workflowStages: ["Stage 1: Passive Probing", "Stage 3: Anvil EVM Spawn", "Stage 4: Active Reentrancy exploit"],
    replayContexts: ["Local Anvil EVM block forking"],
    relatedDocs: ["verification-workflow-sandbox-anvil", "prerequisites-general"]
  },
  {
    id: "modules-ai-breakout",
    title: "Agentic AI Prompt Injection & RCE Fuzzing",
    category: "modules",
    content: "Audits prompt escapes via 'prompt_injection_fuzzer.py' and code execution boundaries via 'code_execution_prober.py'. Active validation routes payloads inside secure gVisor container replicas.",
    tags: ["ai-modules", "prompt-injection", "code-execution-prober", "escape", "gvisor"],
    relatedSchemas: ["AI_INJECTION_ANOMALY Event Contract"],
    relatedCommands: ["vscanx scan <llm-endpoint> --scan-type agentic --verify"],
    workflowStages: ["Stage 1: Passive Probing", "Stage 3: gVisor Spawn", "Stage 4: Escape validation"],
    replayContexts: ["runsc gVisor isolation containment"],
    relatedDocs: ["verification-workflow-sandbox-gvisor", "prerequisites-general"]
  },
  {
    id: "internals-plugin-manager",
    title: "Plugin Discovery Engine Internals",
    category: "internals",
    content: "Dynamic loading inside 'core/plugins/manager.py'. walks packages via 'pkgutil.walk_packages()' and imports modules via 'importlib.import_module()', verifying classes subclassing the baseline 'BaseModule' at startup.",
    tags: ["plugin-discovery", "plugin-manager", "core-plugins-manager"],
    relatedSchemas: ["BaseModule Abstract Class Skeleton"],
    relatedCommands: ["vscanx scan <target> --verify"],
    workflowStages: ["Stage 1: Dynamic Discovery & Module Registration"],
    replayContexts: ["Dynamic class loader instantiation"],
    relatedDocs: ["internals-orchestrator", "cli-scan"]
  },
  {
    id: "internals-orchestrator",
    title: "Runtime Concurrency & Orchestration Internals",
    category: "internals",
    content: "The framework core in 'core/orchestrator.py' handles dynamic thread allocations. Dispatches verification tasks inside a thread-safe 'concurrent.futures.ThreadPoolExecutor' pool featuring task timeouts and circuit breakers.",
    tags: ["concurrency", "threading", "thread-pool", "core-orchestrator"],
    relatedSchemas: ["ThreadPool Executor Descriptors"],
    relatedCommands: ["vscanx scan <target> --verify"],
    workflowStages: ["Stage 2: Event Queueing", "Stage 3: Concurrency Task Allocation"],
    replayContexts: ["ThreadPoolExecutor safe task execution"],
    relatedDocs: ["internals-plugin-manager", "cli-scan"]
  }
];
